name: hw7_env
dependencies:
  - python=3.9
  - decorator=5.1
  - ipykernel=6.6
  - numpy=1.21
  - scipy=1.7
  - matplotlib=3.5
  - pytest=6.2
  - pandas=1.3
  - dataframe_image=0.1
  - plotly=5.7
  - scikit-learn=1.0
  - seaborn=0.11
  - python-kaleido=0.2
